### ISSUE TITLE
Bug no fluxo de seleção de temporizadores e sugestão de melhoria

### ISSUE THREAD

**Issue by lucaslp-dev** [DaniloPnggg/pomodoro#3]
## Descrição do Bug:
Quando clico no botão "Descanso" e dou início ao temporizador, se em seguida eu clico no botão "Longo Descanso", o temporizador é reiniciado corretamente. No entanto, o botão "Começar" já é selecionado automaticamente, o que não deveria acontecer. O comportamento esperado seria que, após o reset do novo temporizador, a aplicação aguardasse a ação do usuário para iniciar a nova contagem regressiva, clicando no botão "Começar".

## Sugestão de Melhoria:
Além de corrigir o bug mencionado acima, gostaria de sugerir uma melhoria na experiência do usuário. Quando um usuário seleciona e inicia um dos temporizadores disponíveis ("Foco", "Descanso" ou "Longo Descanso"), seria interessante desabilitar a interação com os outros botões de seleção de temporizador. Dessa forma, o usuário só poderia interromper, trocar ou reiniciar o temporizador em execução, clicando nos botões "Pausar" ou "Reiniciar", respectivamente.

Essa abordagem evitaria a possibilidade de iniciar acidentalmente um temporizador diferente do desejado durante uma sessão de foco ou descanso em andamento. :)

**Comment by DaniloPnggg** [comment]
bugs corrigidos!!!!!

sugestão de melhoria feita
